version: '3.8'

# Для локальной разработки - собирает образы из исходников
services:
  frontend:
    build:
      context: ../shortener-front
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: /api
    restart: always
    environment:
      - IS_PRODUCTION_ENV=true

  api:
    build:
      context: ../url-shortener
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data/api:/app/storage
    environment:
      - CONFIG_PATH=/app/config/prod-docker.yaml 
      - HTTP_SERVER_PASSWORD=shortener-secret
  
  sso:
    build:
      context: ../sso
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data/sso:/app/storage
    environment:
      - CONFIG_PATH=/app/config/prod-docker.yaml

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8085:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api
      - sso

networks:
  default:
    name: my_app_network

