version: '3.8'

services:
  frontend:
    image: ghcr.io/YOUR_USERNAME/shortener-front:latest
    restart: always
    environment:
      - IS_PRODUCTION_ENV=true

  api:
    image: ghcr.io/YOUR_USERNAME/url-shortener:latest
    restart: always
    volumes:
      - ./data/api:/app/storage
    environment:
      - CONFIG_PATH=/app/config/prod-docker.yaml 
      - HTTP_SERVER_PASSWORD=shortener-secret
  
  sso:
    image: ghcr.io/YOUR_USERNAME/sso:latest
    restart: always
    volumes:
      - ./data/sso:/app/storage
    environment:
      - CONFIG_PATH=/app/config/prod-docker.yaml 

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8085:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api
      - sso

networks:
  default:
    name: my_app_network

