name: Deploy Infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'docker-compose.yaml'
      - 'nginx/**'
  repository_dispatch:
    types: [frontend-updated, api-updated, sso-updated]

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Копируем всё содержимое репозитория в папку на сервере
          source: "./docker-compose.yaml,./nginx/default.conf"
          target: "/root/apps/my-project"

      - name: Apply changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/apps/my-project
            # Подтягиваем образы, если они изменились в compose
            docker compose pull
            # Перезапускаем контейнеры (docker сам поймет, что изменилось)
            docker compose up -d
            # Принудительно перезагружаем nginx внутри контейнера, если изменился только его конфиг
            docker exec my-project-nginx-1 nginx -s reload